///Type classifier for messages in the thread
///
/// 0: Traditional SMS - Standard text messages sent through cellular networks
/// 1: MMS - Multimedia Messaging Service messages containing media
/// 2: RCS (Rich Communication Services) - Enhanced messaging with rich features
/// 3: System Message - Internal system notifications or status messages
/// 4: Chat/IM - Internet-based instant messaging protocols
/// 5: Emergency Messages - High-priority alert messages
/// 6: Voicemail Notifications - Message threads containing voicemail notifications
/// Manufacturer-Specific Extensions
/// 7: Advanced Messaging (Samsung) - Samsung's enhanced messaging protocol
/// 8: Chat+ (Carrier-specific) - Carrier-enhanced messaging services
/// 9: Business Messages - Messages from verified business accounts
/// 10: Auto-generated Messages - Automated system responses or OTP messages
enum AndroidConversationType {
  /// Traditional SMS - Standard text messages sent through cellular networks
  sms(0),

  /// Multimedia Messaging Service messages containing media
  mms(1),

  /// RCS (Rich Communication Services) - Enhanced messaging with rich features
  rcs(2),

  /// System Message - Internal system notifications or status messages
  system(3),

  /// Chat/IM - Internet-based instant messaging protocols
  chat(4),

  /// Emergency Messages - High-priority alert messages
  emergency(5),

  /// Voicemail Notifications - Message threads containing voicemail notifications
  voicemail(6),

  /// Advanced Messaging (Samsung) - Samsung's enhanced messaging protocol
  advancedMessaging(7),

  /// Chat+ (Carrier-specific) - Carrier-enhanced messaging services
  chatPlus(8),

  /// Business Messages - Messages from verified business accounts
  businessMessages(9),

  /// Auto-generated Messages - Automated system responses or OTP messages
  autoGenerated(10);

  const AndroidConversationType(this.value);
  final int value;
}

enum ChatType {
  normal(value: 0),
  compact(value: 1),
  expanded(value: 2);

  const ChatType({required this.value});
  final int value;
}

enum ConversationType {
  traditionalSms(value: 0),
  mms(value: 1),
  rcs(value: 2),
  systemMessage(value: 3),
  chatIm(value: 4),
  emergencyMessages(value: 5),
  voicemailNotifications(value: 6),
  advancedMessaging(value: 7),
  chatPlus(value: 8),
  businessMessages(value: 9),
  autoGeneratedMessages(value: 10);

  const ConversationType({required this.value});
  final int value;
}

enum TypeParser {
  normal(value: 0),
  broadcast(value: 1);

  const TypeParser({required this.value});
  final int value;
}
